# Site settings
author: Chyrelle Lewis
title: Journey to Greatness
header-img: img/home-bg.png
email: chyrellelewis@gmail.com
copyright_name: Chyrelle Lewis
description: > # this means to ignore newlines until "baseurl:"
  From mediocrity  to achieving my  dreams as a Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  urmajesty

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
